"""Generate publication-ready LaTeX table for ANOVA variance decomposition.

Reads data/anova_variance_results_pooled_timbre_source.tsv, data/anova_variance_results_pooled_source.tsv,
or data/anova_variance_results.tsv (generated by loss_variance_analysis.py) and prints a formatted
LaTeX table showing the percentage of variance explained by each factorial term (Amount, Modulation Type,
Feature, Source, 2-Way Interactions, and Higher-Order Residual), with Bonferroni-corrected
significance asterisks displayed to the right of the percentages.

Dynamically adapts columns and table environment depending on whether factors were pooled.
When only 2 factors remain without explicit interaction terms, the residual variance represents
the confounded 2-way interaction and is labeled '2-way Inter.'.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Optional, Union

import pandas as pd

# Method mappings and ordering
HUMAN_ROW = ("human", "Human Listeners")

METHOD_GROUPS = [
    [
        ("mss_log_lin", "MSS Log + Lin."),
        ("mss_rev", "MSS Revisited"),
        ("mfcc", "MFCC"),
    ],
    [
        ("scat1d_log1p", "Scat1D"),
        ("jtfs_log1p", "JTFS"),
    ],
    [
        ("vggish", "VGGish"),
        ("encodec48k", "EnCodec 48~kHz"),
        ("clap2", "MS-CLAP"),
        ("panns_wavegram_logmel", "PANNs WGLM"),
    ],
]

LOSS_FN_ALIASES = {
    "scat1d": "scat1d_log1p",
    "jtfs": "jtfs_log1p",
    "encodec": "encodec48k",
    "encodec48": "encodec48k",
    "encodec24k": "encodec48k",
    "clap": "clap2",
    "panns_wglm": "panns_wavegram_logmel",
}

FACTOR_CONFIG = [
    {
        "key": "amount",
        "source": "rating_stimulus",
        "header": r"\multicolumn{2}{c}{$\sigma\text{ (Amount)}$}",
        "name": "modulation amount",
    },
    {
        "key": "mod",
        "source": "modulation",
        "header": r"\multicolumn{2}{c}{$\sigma\text{ (Mod. Type)}$}",
        "name": "modulation type",
    },
    {
        "key": "feat",
        "source": "feature",
        "header": r"\multicolumn{2}{c}{$\sigma\text{ (Feature)}$}",
        "name": "acoustic feature",
    },
    {
        "key": "source",
        "source": "source",
        "header": r"\multicolumn{2}{c}{$\sigma\text{ (Source)}$}",
        "name": "sound source",
    },
]


def format_sig_figs(val: float, precision: int) -> str:
    """Format a float to a fixed number of significant figures, padding trailing zeros."""
    if val is None or pd.isna(val):
        return ""
    s = f"{val:.{precision}g}"
    if "e" in s or "E" in s:
        return f"{val:.{precision}f}"
    parts = s.split(".")
    if len(parts) == 1:
        needed = precision - len(parts[0])
        return parts[0] + "." + "0" * max(0, needed)
    sig_digits = (
        len(parts[1].lstrip("0"))
        if parts[0] == "0"
        else len(parts[0].lstrip("0")) + len(parts[1])
    )
    needed = precision - sig_digits
    if needed > 0:
        s += "0" * needed
    return s


def format_percentage(val: float, sig_digits: int) -> str:
    """Format a float percentage to fixed significant figures followed by \\%."""
    if val is None or pd.isna(val):
        return ""
    return f"{format_sig_figs(val, sig_digits)}\\%"


def get_asterisks(p_val: float) -> str:
    """Return LaTeX significance asterisks based on p-value."""
    if p_val is None or pd.isna(p_val):
        return ""
    if p_val < 0.001:
        return "$^{***}$"
    elif p_val < 0.01:
        return "$^{**}$"
    elif p_val < 0.05:
        return "$^{*}$"
    return ""


def extract_variance_data(sub_df: pd.DataFrame, sig_digits: int) -> dict[str, tuple[str, str]]:
    """Extract variance percentage and asterisk for each table column."""
    t_map = dict(zip(sub_df["Source"], sub_df["pct_var"]))
    p_map = dict(zip(sub_df["Source"], sub_df["p_bonf"]))

    two_way_pct = sum(v for k, v in t_map.items() if k.count(":") == 1)
    three_way_pct = sum(v for k, v in t_map.items() if k.count(":") == 2)
    residual_pct = next((v for k, v in t_map.items() if "Residual" in k), 0.0)

    # In an unreplicated 2-factor design, residual is mathematically the 2-way interaction
    if two_way_pct == 0.0 and three_way_pct == 0.0 and residual_pct > 0.0:
        two_way_pct = residual_pct

    return {
        "amount": (
            format_percentage(t_map.get("rating_stimulus", 0.0), sig_digits),
            get_asterisks(p_map.get("rating_stimulus")),
        ),
        "mod": (
            format_percentage(t_map.get("modulation", 0.0), sig_digits),
            get_asterisks(p_map.get("modulation")),
        ),
        "feat": (
            format_percentage(t_map.get("feature", 0.0), sig_digits),
            get_asterisks(p_map.get("feature")),
        ),
        "source": (
            format_percentage(t_map.get("source", 0.0), sig_digits),
            get_asterisks(p_map.get("source")),
        ),
        "two_way": (
            format_percentage(two_way_pct, sig_digits),
            "",  # No asterisk for composite 2-way interactions
        ),
        "three_way": (
            format_percentage(three_way_pct, sig_digits),
            "",  # No asterisk for composite 3-way interactions
        ),
        "residual": (
            format_percentage(residual_pct, sig_digits),
            "",  # No asterisk for residual / higher-order interactions
        ),
    }


def format_row(
    method_name: str,
    var_data: dict[str, tuple[str, str]],
    active_factors: list[dict],
    center_cols: list[str],
) -> str:
    """Format a single table row with method, active tested columns (val + ast), and center columns."""
    parts = [f"    {method_name:<18s}"]
    for fc in active_factors:
        val, ast = var_data[fc["key"]]
        val_pad = f"{val:>9s}"
        ast_pad = f"{ast:<8s}" if ast else " " * 8
        parts.append(f"& {val_pad} & {ast_pad}")

    for col in center_cols:
        val, _ = var_data[col]
        val_pad = f"{val:>8s}"
        parts.append(f"& {val_pad}")

    return " ".join(parts) + " \\\\"


def generate_latex_table(
    df: pd.DataFrame,
    sig_digits: int = 3,
    table_env: str = "auto",
    tabcolsep: Optional[str] = None,
    caption: Optional[str] = None,
    label: Optional[str] = None,
) -> str:
    """Generate the complete LaTeX table string from ANOVA results dataframe."""
    df = df.copy()
    if "loss_fn" in df.columns:
        df["canonical_loss"] = df["loss_fn"].map(lambda x: LOSS_FN_ALIASES.get(x, x))

    present_sources = set(df["Source"].unique())
    active_factors = [fc for fc in FACTOR_CONFIG if fc["source"] in present_sources]
    pooled_factors = [fc for fc in FACTOR_CONFIG if fc["source"] not in present_sources]
    is_pooled = len(pooled_factors) > 0

    has_two_way = any(k.count(":") == 1 for k in present_sources)
    has_three_way = any(k.count(":") == 2 for k in present_sources)
    has_residual = any("Residual" in k for k in present_sources)
    residual_is_two_way = has_residual and not has_two_way and not has_three_way

    center_cols: list[str] = []
    center_headers: list[str] = []
    if has_two_way or residual_is_two_way:
        center_cols.append("two_way")
        center_headers.append(r"$\sigma\text{ (2-way Inter.)}$")
    if has_three_way:
        center_cols.append("three_way")
        center_headers.append(r"$\sigma\text{ (3-way Inter.)}$")
    if has_residual and not residual_is_two_way:
        center_cols.append("residual")
        center_headers.append(r"$\sigma\text{ (Higher Order)}$")

    # Determine table environment (table vs table*)
    if table_env == "auto":
        resolved_env = "table" if len(active_factors) <= 2 else "table*"
    else:
        resolved_env = table_env

    # Tabcolsep default
    if tabcolsep is None:
        tabcolsep_val = "6.0pt" if resolved_env == "table" else "4.5pt"
    else:
        tabcolsep_val = tabcolsep

    # Caption and Label defaults
    if caption is None:
        if is_pooled:
            pooled_names = [fc["name"] for fc in pooled_factors]
            if len(pooled_names) > 1:
                pooled_desc = ", ".join(pooled_names[:-1]) + " and " + pooled_names[-1]
            else:
                pooled_desc = pooled_names[0]

            active_desc = ", ".join(fc["name"] for fc in active_factors)
            rem_desc = (
                f"{active_desc}, and two-way interaction variance"
                if residual_is_two_way
                else f"{active_desc}, and residual variance"
            )
            caption_text = (
                f"ANOVA variance decomposition of human listening study responses and audio distance representations "
                f"pooled across {pooled_desc}. Variance components ($\\\\sigma$) indicate the percentage of total variance "
                f"explained by each remaining factorial term: {rem_desc}. Statistical "
                f"significance for main factors is indicated by asterisks based on Bonferroni-corrected $p$-values "
                f"($^{{***}}p < 0.001$, $^{{**}}p < 0.01$, $^{{*}}p < 0.05$; unstarred indicates $p \\\\ge 0.05$)."
            )
        else:
            caption_text = (
                r"ANOVA variance decomposition of human listening study responses and audio distance representations. "
                r"Variance components ($\sigma$) indicate the percentage of total variance explained by each factorial term: "
                r"modulation amount, modulation type, acoustic feature, sound source, two-way interaction terms, and "
                r"higher-order residual variance. Statistical significance for main factors is indicated by asterisks "
                r"based on Bonferroni-corrected $p$-values ($^{*}p < 0.05$, $^{**}p < 0.01$, $^{***}p < 0.001$; "
                r"unstarred indicates $p \ge 0.05$)."
            )
    else:
        caption_text = caption

    if label is None:
        label_text = (
            "tab:anova_variance_decomposition_pooled"
            if is_pooled
            else "tab:anova_variance_decomposition"
        )
    else:
        label_text = label

    lines = []
    lines.append(rf"\begin{{{resolved_env}}}[t]")
    lines.append(r"\centering")
    lines.append(r"\caption{")
    lines.append(caption_text)
    lines.append(r"}")
    lines.append(rf"\label{{{label_text}}}")
    lines.append(r"\vspace{3pt}")
    lines.append(r"\sisetup{")
    lines.append(r"    round-pad = true,")
    lines.append(r"    reset-text-series=false, ")
    lines.append(r"    text-series-to-math=true, ")
    lines.append(r"    mode=text,")
    lines.append(r"    tight-spacing=false,")
    lines.append(r"    separate-uncertainty=false,")
    lines.append(r"    detect-weight=true,")
    lines.append(r"    detect-inline-weight=math,")
    lines.append(r"}")
    lines.append(rf"\setlength{{\tabcolsep}}{{{tabcolsep_val}}}")
    lines.append(r"\begin{tabular}{")
    lines.append(r"    l")
    for _ in active_factors:
        lines.append(r"    r @{\,} l")
    for _ in center_cols:
        lines.append(r"    c")
    lines.append(r"}")
    lines.append(r"    \toprule")

    header_parts = [r"\textbf{Method}"]
    for fc in active_factors:
        header_parts.append(fc["header"])
    header_parts.extend(center_headers)
    lines.append("    " + " & ".join(header_parts) + r" \\")
    lines.append(r"    \midrule")

    # Row 1: Human listening study benchmark
    human_match = df[df["canonical_loss"] == HUMAN_ROW[0]]
    if human_match.empty:
        human_match = df[df["loss_fn"] == HUMAN_ROW[0]]
    if not human_match.empty:
        human_data = extract_variance_data(human_match, sig_digits)
        lines.append(format_row(HUMAN_ROW[1], human_data, active_factors, center_cols))
        lines.append(r"    \midrule")

    # Model rows grouped
    for g_idx, group in enumerate(METHOD_GROUPS):
        if g_idx > 0:
            lines.append(r"    \addlinespace[5pt]")
        for canon_key, display_name in group:
            m_match = df[df["canonical_loss"] == canon_key]
            if m_match.empty:
                m_match = df[df["loss_fn"] == canon_key]
            if m_match.empty:
                continue
            m_data = extract_variance_data(m_match, sig_digits)
            lines.append(format_row(display_name, m_data, active_factors, center_cols))

    lines.append(r"    \bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(rf"\end{{{resolved_env}}}")

    return "\n".join(lines)


def resolve_file_path(path_str: str) -> Path:
    """Resolve file path relative to current working dir, repo root, or script location."""
    p = Path(path_str).expanduser()
    if p.exists():
        return p.resolve()
    repo_root = Path(__file__).resolve().parent.parent.parent
    candidate = (repo_root / path_str).resolve()
    if candidate.exists():
        return candidate
    candidate_script = (Path(__file__).resolve().parent / path_str).resolve()
    if candidate_script.exists():
        return candidate_script

    # Fallback mappings for pooled variance files
    if path_str.endswith("anova_variance_results_pooled.tsv"):
        alt = candidate.with_name("anova_variance_results_pooled_timbre_source.tsv")
        if alt.exists():
            return alt

    return p.resolve()


def main():
    parser = argparse.ArgumentParser(
        description="Print LaTeX ANOVA variance decomposition table from anova_variance_results.tsv to terminal."
    )
    parser.add_argument(
        "input",
        nargs="?",
        default="data/anova_variance_results_pooled_source.tsv",
        help="Path to anova_variance_results_pooled_source.tsv, anova_variance_results_pooled_timbre_source.tsv, or anova_variance_results.tsv (default: data/anova_variance_results_pooled_source.tsv)",
    )
    parser.add_argument(
        "--sig-digits",
        "--sig-figs",
        type=int,
        default=3,
        dest="sig_digits",
        help="Number of significant figures for variance percentages (default: 3).",
    )
    parser.add_argument(
        "--table-env",
        choices=["table", "table*", "auto"],
        default="auto",
        help="LaTeX table environment: 'table', 'table*', or 'auto' (default: 'auto', uses 'table' if <= 2 factors, else 'table*').",
    )
    parser.add_argument(
        "--table-star",
        action="store_true",
        help="Force using \\begin{table*} environment.",
    )
    parser.add_argument(
        "--tabcolsep",
        default=None,
        help="Custom LaTeX \\tabcolsep value (e.g. '5pt', '6pt').",
    )
    parser.add_argument(
        "--caption",
        default=None,
        help="Custom LaTeX caption string.",
    )
    parser.add_argument(
        "--label",
        default=None,
        help="Custom LaTeX label string.",
    )
    parser.add_argument(
        "-o",
        "--output",
        default=None,
        help="Optional path to save generated LaTeX table to a .tex file.",
    )
    parser.add_argument(
        "-q",
        "--quiet",
        action="store_true",
        help="Suppress printing to terminal (useful when exporting only to file).",
    )
    args = parser.parse_args()

    input_path = resolve_file_path(args.input)
    if not input_path.exists():
        sys.stderr.write(f"Error: ANOVA variance results file not found at: {input_path}\n")
        sys.exit(1)

    sep = "\t" if input_path.suffix in [".tsv", ".txt"] else ","
    df = pd.read_csv(input_path, sep=sep)

    table_env = "table*" if args.table_star else args.table_env
    table_latex = generate_latex_table(
        df,
        sig_digits=args.sig_digits,
        table_env=table_env,
        tabcolsep=args.tabcolsep,
        caption=args.caption,
        label=args.label,
    )

    if not args.quiet:
        print(table_latex)

    if args.output:
        out_path = Path(args.output).expanduser().resolve()
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(table_latex, encoding="utf-8")
        sys.stderr.write(f"Table successfully written to: {out_path}\n")


if __name__ == "__main__":
    main()
